### ISSUE TITLE
Windows path problem

### ISSUE THREAD

**Issue by AlexSabur** [m2sd/nuxt-laravel#1]
Hello.
When using the package on windows (without wsl), I encountered a problem that the links for proxy are not generated correctly.

For example: when used default settings and 
``` js
// nuxt.config.js
router: {
    base: '/app/',
},
```
NUXT_OUTPUT_PATH equals "http://localhost:3000//app/__nuxt_laravel"  which does not work
and proxy rules are incorrect
``` js
[
  '**/*',
  '!\\app\\__nuxt_laravel'
]
```
This all leads to php server errors, and the inability to open nuxt files.
As a quick fix, you can use the "slash" package.
``` ts
// https://github.com/m2sd/nuxt-laravel/blob/master/src/module.ts#L136
        ['**/*', `!${slash(path.join(baseUrl, moduleKey))}`],
// https://github.com/m2sd/nuxt-laravel/blob/master/src/module.ts#L238
          slash(path.join(baseUrl, moduleKey)),
```
On windows, this solves the problem, and everything starts to work correctly.
Or is there some other solution to this problem?

**Comment by mentAl-maZe** [comment]
First stable release is coming this weekend, that should resolve your issue.

I'll get back to you once I've pushed

**Comment by mentAl-maZe** [comment]
I didn't have time to finish the tests so I pushed another prerelease.
It's still tagged with `next` so if you run `npm i -D nuxt-laravel@next` it gets updated and the problem should be gone.

Please verify and close the issue if your problem is resolved.

Also checkout the new `swCache` feature :smile:

**Comment by AlexSabur** [comment]
Everything seems to work)
Thanks! ^^
