### ISSUE TITLE
Axios uses wrong port

### ISSUE THREAD

**Issue by DemonsHW** [m2sd/nuxt-laravel#11]
Axios seems to be using wrong default nuxt port 3000.
Can be easly fixed by adding following to nuxt.config.js:

```javascript
config.axios = {
  baseURL: 'http://localhost:3001'
};
```

**Comment by mentAl-maZe** [comment]
Hi @DemonsHW 

Theoretically this is the expected behaviour as all proxying should be handled by `@nuxtjs/proxy`.

The idea is that you do not have to adjust configuration when switching between `dev` and `build`

**Comment by DemonsHW** [comment]
If dev server is on port 3001 and axios tries to fetch something from port 3000 i get CORS error.

**Comment by mentAl-maZe** [comment]
With the default configuration the nuxt dev server is on 3000 and the Laravel dev server is on 3001.
Never had a CORS issue before... may be due to update.

Can you provide some context:
Nuxt Version
Laravel Version
Your nuxt config (if you don't mind)

**Comment by DemonsHW** [comment]
As far as i know it build in browser feature.

Nuxt Version: 2.13.3
Laravel Version: 7.19.1 

nuxt.config does not have anything special if you really need it i can share it.

**Comment by DemonsHW** [comment]
> PS: Are you maybe trying to access the dev server from port 3001?
Yes but when i try to use port 3000 it doesn't go through laravel and all my api calls are whatever is in file_get_contents

**Comment by mentAl-maZe** [comment]
Ok, so, a few things to check:
* The module does not yet support `universal` mode, but in theory it should give you a disabled message if your nuxt is configured that way
* In Laravel (`m2s/laravel-nuxt`): The `config('nuxt.source')` setting should read the `NUXT_OUTPUT_PATH` environment variable (this get's overwritten in development to point to the nuxt dev server), can you maybe share your nuxt route implementation
* In Laravel (`m2s/laravel-nuxt`): The `config('nuxt.prefix')` setting should correspond to your `router.base` setting in `nuxt.config`

**Comment by DemonsHW** [comment]
Base is set to '/' in both nuxt.config and laravel config

web.php:
```php
//above are some api's
Route::get(
  '/{path?}',
  function($request) {
    return file_get_contents(public_path('spa.html'));
  }
)->where('path', '.*')->name('nuxt');
```

But whenever i use port 3000 it doesn't matter what is in web.php beacause it is never reached.

**Comment by mentAl-maZe** [comment]
I see your problem:
You have to use the environment variable in order for  the dev functionality to work

```php
Route::get(
  '/{path?}',
  function($request) {
    return file_get_contents(env('NUXT_OUTPUT_PATH', public_path('spa.html')));
  }
)->where('path', '.*')->name('nuxt');
```

**Comment by DemonsHW** [comment]
> 
> 
> I see your problem:
> You have to use the environment variable in order for the dev functionality to work
> 
> ```
> Route::get(
>   '/{path?}',
>   function($request) {
>     return file_get_contents(env('NUXT_OUTPUT_PATH', public_path('spa.html')));
>   }
> )->where('path', '.*')->name('nuxt');
> ```

Thanks for reply but like i said it doesn't matter what is in web.php because it never gets there.

I just changed it and it stull doesn't work.
I get nuxt "This page could not be found" response from all laravel routes in web.php.

**Comment by mentAl-maZe** [comment]
Hmm.... :thinking: 
Are you using nuxt programmatically (with an express server or something similar)?

**Comment by DemonsHW** [comment]
> 
> 
> Hmm.... 🤔
> Are you using nuxt programmatically (with an express server or something similar)?

I'm not sure what you mean by that.
I use "npm run nuxt:dev"

**Comment by mentAl-maZe** [comment]
Can you please post the `scripts` section of your `package.json`

**Comment by DemonsHW** [comment]
> 
> 
> Can you please post the `scripts` section of your `package.json`

 "scripts": {
        "dev": "npm run development",
        "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch": "npm run development -- --watch",
        "watch-poll": "npm run watch -- --watch-poll",
        "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
        "prod": "npm run production",
        "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "nuxt:dev": "nuxt",
        "nuxt:build": "nuxt build",
        "nuxt:generate": "nuxt generate",
        "nuxt:start": "nuxt start"
    },

**Comment by mentAl-maZe** [comment]
Weird... :confused: 
In theory it should work...

> I just changed it and it still doesn't work.
> I get nuxt "This page could not be found" response from all laravel routes in web.php.

This does actually sounds as if it works...
If you have other routes can you maybe try to set `router.base = '/app/'` and `Route::get('/app/{path?}')`

**Comment by DemonsHW** [comment]
> This does actually sounds as if it works...
> If you have other routes can you maybe try to set `router.base = '/app/'` and `Route::get('/app/{path?}')`

Cannot GET ...

Still doesn't go through laravel.

> PS: have you used the stater repo (https://github.com/m2sd/nuxt-laravel-starter)?
I had a project already thats why i didn't use it but i will look into it.

**Comment by DemonsHW** [comment]
> 
> 
> > This does actually sounds as if it works...
> > If you have other routes can you maybe try to set `router.base = '/app/'` and `Route::get('/app/{path?}')`
> 
> Cannot GET ...
> 
> Still doesn't go through laravel.
> 
> > PS: have you used the stater repo (https://github.com/m2sd/nuxt-laravel-starter)?

I had a project already thats why i didn't use it but i will look into it.

**Comment by DemonsHW** [comment]
> This does actually sounds as if it works...
> If you have other routes can you maybe try to set `router.base = '/app/'` and `Route::get('/app/{path?}')`

Route answer's with Cannot GET ...

Still doesn't go through laravel.
> PS: have you used the stater repo (https://github.com/m2sd/nuxt-laravel-starter)?

I had a project already thats why i didn't use it but i will look into it.

**Comment by GautierDele** [comment]
You don't really need to set the base path in laravel's routes:
```php
Route::post(
    'stripe/webhook',
    '\App\Http\Controllers\WebhookController@handleWebhook'
);

Route::get('{path}', '\\'.Pallares\LaravelNuxt\Controllers\NuxtController::class)->name('nuxt')->where('path', '^(?!nova|admin.*$).*');
```

Laravel's routes go through api before web so when the router goes to the end i'm sending him to Nuxt.

Going through proxy is mandatory in this case, you can find my example below:
```js
axios: {
    prefix: '/api',
    proxy: {
      '/api': process.env.API_HOST
    },
    https: process.env.API_HTTPS === 'true'
  },
```

To force nuxt not to be at the root:
```js
router: {
    base: '/app/'
  }
```

Can you provide us maybe a screenshot of the error + host asked + current host ?

**Comment by DemonsHW** [comment]
If base is set to "/app/":

- web.php:
```php

Route::get('/foo', function(){
  return "bar";
});

Route::get(
  '/app/{path?}',
  function($request) {
    // Fetch and display the page from the render path on nuxt dev server or fallback to static file
    return file_get_contents(env('NUXT_OUTPUT_PATH', public_path('app/spa.html')));
  }
)->where('path', '.*')
// Redirect to Nuxt from within Laravel
// by using Laravels route helper
// e.g.: `route('nuxt', ['path' => '/<nuxtPath>'])`
->name('nuxt');
```

Requesting get from "http://localhost:3000/foo" results in "Cannot GET /foo"


If base is set to '/':

Requesting get from "http://localhost:3000/foo" results in:
![afbeelding](https://user-images.githubusercontent.com/28757930/87924020-999b4000-ca7e-11ea-8f2b-b00366b5e1d6.png)

**Comment by DemonsHW** [comment]
> ```js
> axios: {
>     prefix: '/api',
>     proxy: {
>       '/api': process.env.API_HOST
>     },
>     https: process.env.API_HTTPS === 'true'
>   },
> ```

Doesn't seem to help

**Comment by DemonsHW** [comment]
> PS: have you used the stater repo (https://github.com/m2sd/nuxt-laravel-starter)?
nuxt-laravel-starter seems to be working. I will try to find out what is different about my project and nuxt-laravel-starter
