### ISSUE TITLE
Wrong named output file in publicDir

### ISSUE THREAD

**Issue by feam-codes** [m2sd/nuxt-laravel#2]
Hi.

Referring to the documentation I think there is an error in your code. The [documentation](https://github.com/m2sd/nuxt-laravel#path-resolution-inside-publicdir) said:

> If nuxtConfig.router.base **is not set** the SPA will be generated in the publicDir root with an index file name of spa.html.

> If nuxtConfig.router.base **is set** the SPA will be generated in a corresponding location inside publicDir with the default index file name index.html.

So i was wondering why i got a spa.html in my output folder. After a quick look in your module I think your if-condition has to be changed:
https://github.com/m2sd/nuxt-laravel/blob/bf42b27868ad18c96a996e7587210755426503c8/lib/options.js#L40

Kind regards,
Flo

**Comment by mentAl-maZe** [comment]
Hi,
sry for the long silence, i was away over new years and since i got back i have been swamped with work...
I'll look at it over the weekend

**Comment by mentAl-maZe** [comment]
I fixed this right away as it was 'just' a faulty condition.
As you already pointed out all i had to do was switch the two names around.
Sorry again for the long response time.
