### ISSUE TITLE
How to access to cookies and sessions from nuxt side

### ISSUE THREAD

**Issue by gitllermopalafox** [m2sd/nuxt-laravel#8]
Hi, a lot thanks for your effort and time to keep this project shining.

I read in the features that you can access to laravel cookies and session state... is there any helper available for this? or is like "old school" by ajax call and in your controller (IMHO I don't like it)... 
``` php
 return session()->all()
```

I'm using nuxt-laravel-starter  (https://github.com/m2sd/nuxt-laravel-starter)

Thanks in advance.

**Comment by GautierDele** [comment]
What's wrong with cookies ? I can confirm having a "PHP_SESS_ID" cookie that should do the job. Other cookies should be accessible from front side.

I don't really know what was meant by @mentAl-maZe when he was saying that you can share the session state. You might be able to access the session while requesting laravel since your cookies have the "PHP_SESS_ID" available.

Be aware that this is not working if you are working with a PWA.

**Comment by gitllermopalafox** [comment]
Hi @GautierDele thanks for your answer. 

I've been trying to get it working without success... 

I try to login with the laravel default auth and then get user status (if the user is logged in or not) but I always get false.

The short version: it seems axios is not sending back the cookies to the back.

The long version:

This is part of my code in the front:

User login: 

``` javascript
this.$axios
      .$post('/login', { email: 'test@test.com', password: '123456' })
      .then(console.log)
```

Check user status:
``` javascript
this.$axios.$post('/loggedin', {}).then(console.log)
```

nuxt.config.js -> Axios module configuration
```javascript
...
  axios: {
    baseURL: "http://localhost:3000", // .custom-domain.test,
    credentials: true
  },
```
----

In the backend:

My routes file (web.php) I use the web guard:

```php
Route::get('/', function () {
    return view('welcome');
});

Route::namespace('Api') // <--- Just for better controllers structure /app/Http/Controllers/Api
    ->group(function () {
        Route::post('/signup', 'Auth\RegisterController@register');
        Route::post('/login', 'Auth\LoginController@login');
        Route::post('/loggedin', 'Auth\LoginController@isLoggedIn');
    });

Route::get('/app{path}', '\\' . Pallares\LaravelNuxt\Controllers\NuxtController::class)->name('nuxt')->where('path', '.*');

```

In my LoginController the only difference with original one is the type of response, I return a json instead of redirect...

```php
...
    protected function sendLoginResponse(Request $request)
    {
        $request->session()->regenerate();

        $this->clearLoginAttempts($request);

        return $this->authenticated($request, $this->guard()->user());
    }

    protected function authenticated(Request $request, $user)
    {
        return response()->json($user);
    }
...
```

In the session.php file I have tried with different settings like:

```php
...
'domain' => '.localhost',  //.custom-domain.test,
'http_only' => false | true,
'same_site' => 'lax',
...
etc...
```
---

Can you help me with some advices of how you got it work?

Thanks in advance.

**Comment by gitllermopalafox** [comment]
Hi again, after trying several settings, I got it working with... in the session.php file the "domain" option set to ".my-custom-domain.test" nothing else. I couldn't get it to work only with localhost.

**Comment by mentAl-maZe** [comment]
@gitllermopalafox 
Sry for the long silence, i've been crazy busy and didn't find any time for foss stuff...

@GautierDele Thanks for pitching in :+1: 

I'm happy your problem is resolved, but could you maybe provide a repo to reproduce your original issue, so i can investigate (once i have time...)
